package:
  name: nose
  version: !!str 1.3.3

source:
  fn: nose-1.3.3.tar.gz
  url: https://pypi.python.org/packages/source/n/nose/nose-1.3.3.tar.gz
  md5: 42776061bf5206670cb819176dc78654
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - nose = nose:main
    #
    # Would create an entry point called nose that calls nose.main()

    - nosetests = nose:run_exit
    - nosetests-2.7 = nose:run_exit

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - nose
    - nose.ext
    - nose.plugins
    - nose.sphinx
    - nose.tools

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - nosetests --help
    - nosetests-2.7 --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://readthedocs.org/docs/nose/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'nose extends unittest to make testing easier'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
